name: projects
description: A unified university data application for Smart Campus Insights.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^7.0.0
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  http: ^0.13.5
  html: ^0.15.4
  intl: ^0.18.0
  crypto: ^3.0.2
  fl_chart: ^0.65.0
  percent_indicator: ^4.2.3
  shimmer: ^2.0.0
  flutter_chat_ui: ^1.6.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21



flutter:
  uses-material-design: true
  assets:
    - assets/images/
